E_Commerce/E_Commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .import views


urlpatterns = [
    # error page
    path('404',views.Error404,name='404'),
    
    path('admin/', admin.site.urls),
    path('base/', views.BASE, name='base'),
    
    path('', views.HOME, name='home'),
    path('about',views.ABOUT,name='about'),
    path('contact', views.CONTACT, name='contact'),
    path('product', views.PRODUCT, name='product'),
    path('product/<str:id>',views.PRODUCT_DETAILS,name='product_detail'),
    path('search',views.SEARCH,name='search'),

    
    # Account url
    path('account/register',views.REGISTER,name='register'),
    path('account/login',views.LOGIN,name='login'),
    path('account/logout',views.LOGOUT,name='logout'),
    path('account/profile',views.PROFILE,name='profile'),
    path('account/profile/update',views.PROFILE_UPDATE,name='profile_update'),
    path('accounts/',include('django.contrib.auth.urls')),
    
    # Cart url
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
    path('cart/checkout/',views.Checkout,name='checkout'),
    path('cart/checkout/placeorder',views.PLACE_ORDER,name='place_order'),
    path('Your_Order',views.YOUR_ORDER,name='your_order'),
    
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

E_Commerce/app/models.py
import datetime
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User


class Slider(models.Model):
    DISCOUNT_DEAL =(
        ('HOT_DEALS','HOT_DEALS'),
        ('NEW_ARRIVALS','NEW_ARRIVALS')
    )
    Image=models.ImageField(upload_to='media/slider_image')
    Discount_Deal=models.CharField(choices=DISCOUNT_DEAL,max_length=100)
    SALE =models.IntegerField()
    Brand_Name=models.CharField(max_length=200)
    Discount=models.IntegerField()
    Link=models.CharField(max_length=200)

    def __str__(self):
        return self.Brand_Name
    
class BannerArea(models.Model):
    image = models.ImageField(upload_to='media/banner_img')
    Discount_Deal=models.CharField(max_length=100)
    Quote=models.CharField(max_length=100)
    Discount=models.IntegerField()
    Link=models.CharField(max_length=200,null=True)
     
    def __str__(self) -> str:
        return self.Quote   
    
class Main_Category(models.Model):
    name=models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return self.name  
    
class Category(models.Model):
    main_category = models.ForeignKey(Main_Category,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return self.name + "--" + self.main_category.name  
    
class Sub_Categories(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE) 
    name = models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return self.category.main_category.name + " -- " + self.category.name + " -- " + self.name
    
class Section(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return self.name
    
class Color(models.Model):
    code = models.CharField(max_length=100)    
    
    def __str__(self) -> str:
        return self.code
 
class Brand(models.Model):
    name = models.CharField(max_length=100)    
    
    def __str__(self) -> str:
        return self.name
    
class Product(models.Model):
    total_quantity = models.IntegerField()
    Availability = models.IntegerField()
    featured_image = models.CharField(max_length=100)     
    product_name = models.CharField(max_length=100) 
    Brand = models.ForeignKey(Brand,on_delete=models.CASCADE,null=True)
    price = models.IntegerField()
    Discount = models.IntegerField()
    tax = models.IntegerField(blank=True,null=True)
    delivery_charge = models.IntegerField(blank=True, null=True)
    Product_Information = RichTextField(null=True)
    model_name = models.CharField(max_length=100)
    Categories = models.ForeignKey(Category,on_delete=models.CASCADE)
    color = models.ForeignKey(Color,on_delete=models.CASCADE,null=True)
    Tags = models.CharField(max_length=100)
    Description = RichTextField(null=True)
    section = models.ForeignKey(Section,on_delete=models.DO_NOTHING)
    
    def __str__(self) -> str:
        return self.product_name
    
    
class Product_Image(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE) 
    Image_url = models.CharField(max_length=200)
    
class Additional_Information(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)  
    specification = models.CharField(max_length=100)           
    detail = models.CharField(max_length=200)
    
class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    address = models.TextField()
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    postcode = models.IntegerField()
    phone = models.IntegerField()
    email = models.EmailField(max_length=100)
    payment_id = models.CharField(max_length=300,blank=True,null=True)
    paid = models.BooleanField(default=False,null=True)
    date = models.DateField(default=datetime.datetime.today)
    amount = models.CharField(max_length=100,blank=True)
    
    def __str__(self) -> str:
        return self.user.username
    
class OrderItem(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    order = models.ForeignKey(Order,on_delete=models.CASCADE,null=True)
    product = models.CharField(max_length=200)
    image = models.ImageField(upload_to='assets/img/')    
    quantity = models.IntegerField()
    price = models.IntegerField()
    total = models.IntegerField()
    
    def __str__(self) -> str:
        return self.order.user.username
    
class Event(models.Model):
    event_name = models.CharField(max_length=200)
    event_date = models.DateTimeField()
    
    def __str__(self) -> str:
        return self.event_name
    

    

E_Commerce/templates/Main/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<main>
    <!-- page-banner-area-start -->
    <div class="page-banner-area page-banner-height" data-background="{% static 'assets/img/banner/page-banner-3.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="page-banner-content text-center">
                        <h4 class="breadcrumb-title">Contact Us</h4>
                        <div class="breadcrumb-two">
                            <nav>
                               <nav class="breadcrumb-trail breadcrumbs">
                                  <ul class="breadcrumb-menu">
                                     <li class="breadcrumb-trail">
                                        <a href="index.html"><span>Home</span></a>
                                     </li>
                                     <li class="trail-item">
                                        <span>Contact Us</span>
                                     </li>
                                  </ul>
                               </nav> 
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- page-banner-area-end -->

    <!-- location-area-start -->
    <div class="location-area pt-70 pb-25">
        <div class="container">
            <div class="row mb-25">
                <div class="col-xl-12">
                    <div class="abs-section-title text-center">
                        <span>LOCATION STORE</span>
                        <h4>Where We Are</h4>
                        <p>The perfect way to enjoy brewing tea on low hanging fruit to identify. Duis autem vel eum iriure dolor in hendrerit <br> in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-3 col-lg-3 col-md-6">
                    <div class="location-item mb-30">
                        <div class="location-image w-img mb-20">
                            <img src="{% static 'assets/img/location/location-1.jpg' %}" alt="">
                        </div>
                        <h6>26 Rue Pelleport - Paris</h6>
                        <div class="sm-item-loc sm-item-border mb-20">
                            <div class="sml-icon mr-20">
                                <i class="fal fa-map-marker-alt"></i>
                            </div>
                            <div class="sm-content">
                                <span>Find us</span>
                                <p>Rue Saint-Antoine, Paris, France  </p>  
                            </div>
                        </div>
                        <div class="sm-item-loc sm-item-border mb-20">
                            <div class="sml-icon mr-20">
                                <i class="fal fa-phone-alt"></i>
                            </div>
                            <div class="sm-content">
                                <span>Call us</span>
                                <p><a href="tel:+8804568">(+100) 123 456 7890</a></p>  
                            </div>
                        </div>
                        <div class="sm-item-loc mb-20">
                            <div class="sml-icon mr-20">
                                <i class="fal fa-envelope"></i>
                            </div>
                            <div class="sm-content">
                                <span>Mail us</span>
                                <p><a href="https://themepure.net/cdn-cgi/l/email-protection#a2d1d6cdd0c7e2c1cdcfd2c3ccdb8cc1cdcf"><span class="__cf_email__" data-cfemail="3744435845527754585a4756594e1954585a">[email&#160;protected]</span></a></p>  
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-6">
                    <div class="location-item mb-30">
                        <div class="location-image w-img mb-20">
                            <img src="{% static 'assets/img/location/location-2.jpg' %}" alt=""/>
                        </div>
                        <h6>150 Stanley Rd - London</h6>
                        <div class="sm-item-loc sm-item-border mb-20">
                            <div class="sml-icon mr-20">
                                <i class="fal fa-map-marker-alt"></i>
                            </div>
                            <div class="sm-content">
                                <span>Find us</span>
                                <p>Brick Ln, Spitalfields, London E1, UK</p>  
                            </div>
                        </div>
                        <div class="sm-item-loc sm-item-border mb-20">
                            <div class="sml-icon mr-20">
                                <i class="fal fa-phone-alt"></i>
                            </div>
                            <div class="sm-content">
                                <span>Call us</span>
                                <p><a href="tel:+8804568">(+100) 123 456 7890</a></p>  
                            </div>
                        </div>
                        <div class="sm-item-loc mb-20">
                            <div class="sml-icon mr-20">
                                <i class="fal fa-envelope"></i>
                            </div>
                            <div class="sm-content">
                                <span>Mail us</span>
                                <p><a href="https://themepure.net/cdn-cgi/l/email-protection#4b383f24392e0b2824263b2a253265282426"><span class="__cf_email__" data-cfemail="5d2e29322f381d3e32302d3c3324733e3230">[email&#160;protected]</span></a></p>  
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-6">
                    <div class="location-item mb-30">
                        <div class="location-image w-img mb-20">
                            <img src="{% static 'assets/img/location/location-3.jpg' %}" alt="">
                        </div>
                        <h6>1357 Prospect - New York</h6>
                        <div class="sm-item-loc sm-item-border mb-20">
                            <div class="sml-icon mr-20">
                                <i class="fal fa-map-marker-alt"></i>
                            </div>
                            <div class="sm-content">
                                <span>Find us</span>
                                <p>Atlantic, Brooklyn, New York, US</p>  
                            </div>
                        </div>
                        <div class="sm-item-loc sm-item-border mb-20">
                            <div class="sml-icon mr-20">
                                <i class="fal fa-phone-alt"></i>
                            </div>
                            <div class="sm-content">
                                <span>Call us</span>
                                <p><a href="tel:+8804568">(+100) 123 456 7890</a></p>  
                            </div>
                        </div>
                        <div class="sm-item-loc mb-20">
                            <div class="sml-icon mr-20">
                                <i class="fal fa-envelope"></i>
                            </div>
                            <div class="sm-content">
                                <span>Mail us</span>
                                <p><a href="https://themepure.net/cdn-cgi/l/email-protection#285b5c475a4d684b474558494651064b4745"><span class="__cf_email__" data-cfemail="a7d4d3c8d5c2e7c4c8cad7c6c9de89c4c8ca">[email&#160;protected]</span></a></p>  
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-6">
                    <div class="location-item mb-30">
                        <div class="location-image w-img mb-20">
                            <img src="{% static 'assets/img/location/location-4.jpg' %}" alt="">
                        </div>
                        <h6>86 Georgia Rd - Mardrid</h6>
                        <div class="sm-item-loc sm-item-border mb-20">
                            <div class="sml-icon mr-20">
                                <i class="fal fa-map-marker-alt"></i>
                            </div>
                            <div class="sm-content">
                                <span>Find us</span>
                                <p>Calle del Correo, 4, Madrid, Spain</p>  
                            </div>
                        </div>
                        <div class="sm-item-loc sm-item-border mb-20">
                            <div class="sml-icon mr-20">
                                <i class="fal fa-phone-alt"></i>
                            </div>
                            <div class="sm-content">
                                <span>Call us</span>
                                <p><a href="tel:+8804568">(+100) 123 456 7890</a></p>  
                            </div>
                        </div>
                        <div class="sm-item-loc mb-20">
                            <div class="sml-icon mr-20">
                                <i class="fal fa-envelope"></i>
                            </div>
                            <div class="sm-content">
                                <span>Mail us</span>
                                <p><a href="https://themepure.net/cdn-cgi/l/email-protection#82f1f6edf0e7c2e1edeff2e3ecfbace1edef"><span class="__cf_email__" data-cfemail="82f1f6edf0e7c2e1edeff2e3ecfbace1edef">[email&#160;protected]</span></a></p>  
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- location-area-end -->

    <!-- cmamps-area-start -->
    <div class="cmamps-area">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1899531.5831083965!2d105.806381!3d21.58504!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x515f4860ede9e108!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBDw7RuZyBuZ2jhu4cgVGjDtG5nIHRpbiB2w6AgVHJ1eeG7gW4gdGjDtG5n!5e0!3m2!1sen!2sus!4v1644226635446!5m2!1sen!2sus"></iframe>
    </div>
    <!-- cmamps-area-end -->

    <!-- cta-area-start -->
    <section class="cta-area d-ldark-bg pt-55 pb-10">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="cta-item cta-item-d mb-30">
                        <h5 class="cta-title">Follow Us</h5>
                        <p>We make consolidating, marketing and tracking your social media website easy.</p>
                        <div class="cta-social">
                            <div class="social-icon">
                                <a href="#" class="facebook"><i class="fab fa-facebook-f"></i></a>
                                <a href="#" class="twitter"><i class="fab fa-twitter"></i></a>
                                <a href="#" class="youtube"><i class="fab fa-youtube"></i></a>
                                <a href="#" class="linkedin"><i class="fab fa-linkedin-in"></i></a>
                                <a href="#" class="rss"><i class="fas fa-rss"></i></a>
                                <a href="#" class="dribbble"><i class="fab fa-dribbble"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="cta-item mb-30">
                        <h5 class="cta-title">Sign Up To Newsletter</h5>
                        <p>Join 60.000+ subscribers and get a new discount coupon  on every Saturday.</p>
                        <div class="subscribe__form">
                            <form action="#">
                                <input type="email" placeholder="Enter your email here...">
                                <button>subscribe</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="cta-item mb-30">
                        <h5 class="cta-title">Download App</h5>
                        <p>DukaMarket App is now available on App Store & Google Play. Get it now.</p>
                        <div class="cta-apps">
                            <div class="apps-store">
                                <a href="#"><img src="{% static 'assets/img/brand/app_ios.png' %}" alt=""></a>
                                <a href="#"><img src="{% static 'assets/img/brand/app_android.png' %}" alt=""></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <!-- cta-area-end -->

</main>


{% endblock %}

E_Commerce/templates/Main/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}




<div class="tp-wrapper m-5">
    <div class="row g-0">
        {% for i in product %}
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
            <div class="product__item product__item-d">
                <div class="product__thumb fix">
                    <div class="product-image w-img">
                        <a href="product/{{i.id}}">
                            <img src="{{i.featured_image}}" alt="product" style="height: 200px;">
                        </a>
                    </div>
                    <div class="product-action">
                        <a href="#" class="icon-box icon-box-1" data-bs-toggle="modal"
                            data-bs-target="#productModalId-{{forloop.counter}}">
                            <i class="fal fa-eye"></i>
                            <i class="fal fa-eye"></i>
                        </a>
                        <a href="#" class="icon-box icon-box-1">
                            <i class="fal fa-heart"></i>
                            <i class="fal fa-heart"></i>
                        </a>
                        <a href="#" class="icon-box icon-box-1">
                            <i class="fal fa-layer-group"></i>
                            <i class="fal fa-layer-group"></i>
                        </a>
                    </div>
                </div>
                <div class="product__content-3">
                    <h6><a href="product-details.html">{{i.product_name|truncatewords:8}}</a>
                    </h6>
                    <div class="rating mb-5">
                        <ul>
                            <li><a href="#"><i class="fal fa-star"></i></a></li>
                            <li><a href="#"><i class="fal fa-star"></i></a></li>
                            <li><a href="#"><i class="fal fa-star"></i></a></li>
                            <li><a href="#"><i class="fal fa-star"></i></a></li>
                            <li><a href="#"><i class="fal fa-star"></i></a></li>
                        </ul>
                        <span>(01 review)</span>
                    </div>
                    <div class="price mb-10">
                        <span>${{i.price}}</span>
                    </div>
                </div>
                <div class="product__add-cart-s text-center">
                    <a href="{% url 'cart_add' i.id %}"
                        class="cart-btn d-flex mb-10 align-items-center justify-content-center w-100">
                        Add to Cart
                    </a>
                    <button type="button" class="wc-checkout d-flex align-items-center justify-content-center w-100"
                        data-bs-toggle="modal" data-bs-target="#productModalId-{{forloop.counter}}">
                        Quick View
                    </button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<!-- shop modal start -->
{% for i in product %}
<div class="modal fade" id="productModalId-{{forloop.counter}}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered product__modal" role="document">
        <div class="modal-content">
            <div class="product__modal-wrapper p-relative">
                <div class="product__modal-close p-absolute">
                    <button data-bs-dismiss="modal"><i class="fal fa-times"></i></button>
                </div>
                <div class="product__modal-inner">
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            <div class="product__modal-box">
                                <div class="tab-content" id="modalTabContent">
                                    <div class="tab-pane fade show active" id="nav1" role="tabpanel"
                                        aria-labelledby="nav1-tab">
                                        <div class="product__modal-img w-img">
                                            <img src="{{i.product_image_set.first.Image_url}}" alt=""
                                                style="height: 400px;width: 400px;">
                                        </div>
                                    </div>
                                    {% for image in i.product_image_set.all %}
                                    <div class="tab-pane fade show " id="nav{{image.id}}" role="tabpanel"
                                        aria-labelledby="nav{{image.id}}-tab">
                                        <div class="product__modal-img w-img">
                                            <img src="{{image.Image_url}}" alt="" style="height: 400px;width: 400px;">
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                                <ul class="nav nav-tabs" id="modalTab" role="tablist">
                                    {% for image in i.product_image_set.all %}
                                    <li class="nav-item" role="presentation">
                                        <button class="nav-link" id="nav{{image.id}}-tab" data-bs-toggle="tab"
                                            data-bs-target="#nav{{image.id}}" type="button" role="tab"
                                            aria-controls="nav{{image.id}}" aria-selected="true">
                                            <img src="{{image.Image_url}}" alt="" style="height: 85px; width:85px;">
                                        </button>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            <div class="product__modal-content">
                                <h4><a href="product-details.html">{{i.product_name}}</a></h4>
                                <div class="product__review d-sm-flex">
                                    <div class="rating rating__shop mb-10 mr-30">
                                        <ul>
                                            <li><a href="#"><i class="fal fa-star"></i></a></li>
                                            <li><a href="#"><i class="fal fa-star"></i></a></li>
                                            <li><a href="#"><i class="fal fa-star"></i></a></li>
                                            <li><a href="#"><i class="fal fa-star"></i></a></li>
                                            <li><a href="#"><i class="fal fa-star"></i></a></li>
                                        </ul>
                                    </div>
                                    <div class="product__add-review mb-15">
                                        <span>01 review</span>
                                    </div>
                                </div>
                                <div class="product__price">
                                    <span>${{i.price}}</span>
                                </div>
                                <div class="product__modal-des mt-20 mb-15">
                                    <ul>
                                        <li><a href="#">{{i.Product_Information|safe|truncatechars:600}}</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="product__stock mb-20">
                                    <span class="mr-10">Availability :</span>
                                    <span>{{i.Availability}} in stock</span>
                                </div>
                                <div class="product__modal-form">
                                    <form action="#">
                                        <div class="pro-quan-area d-lg-flex align-items-center">
                                            <div class="product-quantity mr-20 mb-25">
                                                <div class="cart-plus-minus p-relative"><input type="text" value="1" />
                                                </div>
                                            </div>
                                            <div class="pro-cart-btn mb-25">
                                                <a href="{% url 'cart_add' i.id %}" class="cart-btn" type="submit">Add
                                                    to cart</a>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="product__stock mb-30">
                                    <ul>
                                        <li><a href="#">
                                                <span class="sku mr-10">Model Name:</span>
                                                <span>{{i.model_name}}</span></a>
                                        </li>
                                        <li><a href="#">
                                                <span class="cat mr-10">Categories:</span>
                                                <span>{{i.Categories}}</span></a>
                                        </li>
                                        <li><a href="#">
                                                <span class="tag mr-10">Tags:</span>
                                                <span>{{i.Tags}}</span></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- shop modal end -->
{% endfor %}

{% endblock %}